// Code generated by MockGen. DO NOT EDIT.
// Source: rabbitmq.go

// Package mocks is a generated GoMock package.
package broker

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	amqp "github.com/streadway/amqp"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConnection) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnection)(nil).Close))
}

// Consume mocks base method.
func (m *MockConnection) Consume(queue string, consumeFunc func(amqp.Delivery)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Consume", queue, consumeFunc)
}

// Consume indicates an expected call of Consume.
func (mr *MockConnectionMockRecorder) Consume(queue, consumeFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockConnection)(nil).Consume), queue, consumeFunc)
}

// Publish mocks base method.
func (m *MockConnection) Publish(routingKey string, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", routingKey, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockConnectionMockRecorder) Publish(routingKey, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockConnection)(nil).Publish), routingKey, body)
}

// QueueBind mocks base method.
func (m *MockConnection) QueueBind(queuesBind ...*queueBinding) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range queuesBind {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueueBind", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueBind indicates an expected call of QueueBind.
func (mr *MockConnectionMockRecorder) QueueBind(queuesBind ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueBind", reflect.TypeOf((*MockConnection)(nil).QueueBind), queuesBind...)
}
